### ISSUE TITLE
Bug: Package dependency failure "github.com/nats-io/gnatsd/hashmap"

### ISSUE THREAD

**Issue by michaelchihuyho** [glycerine/tmframe#1]
[Referenced package](https://github.com/glycerine/tmframe/blob/master/dedup.go#L5) doesn't exist anymore in [gnatsd](https://github.com/nats-io/gnatsd)!

**Comment by glycerine** [comment]
It's vendored (here: https://github.com/glycerine/tmframe/tree/master/vendor/github.com/nats-io/gnatsd/hashmap), so if you are building with go1.5.3 and not go1.6, then at the bash prompt you should do

 export GO15VENDOREXPERIMENT=1

before "go install/go build" based building.

Or just use the Makefile by typing "make", which will set the env var for you.

**Comment by glycerine** [comment]
Thanks for pointing this out, @michaelchihuyho. As a backup to the backup of having stuff vendored, I've made a separate repo with this code, https://github.com/glycerine/hashmap-nats.
